<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
	  
	  
	<!--Optimizations-->
	  <IlcOptimizationPreference>Size</IlcOptimizationPreference>
	  <TrimMode>full</TrimMode>
	  <PublishTrimmed>true</PublishTrimmed>
	  <Platforms>AnyCPU;x64</Platforms>
    <!--End of Optimizations-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
    <EmbeddedResource Remove="Assets\**" />
    <None Remove="Assets\**" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DevoidEngine.SourceGen\DevoidEngine.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>


	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevoidEngine\DevoidEngine.csproj" />
  </ItemGroup>

</Project>
