using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DevoidEngine.SourceGen.MetadataGeneration
{
    internal static class ClassDBRegistryEmitter
    {
        public static void Emit(
            SourceProductionContext context,
            IEnumerable<INamedTypeSymbol> classes)
        {
            INamedTypeSymbol[] symbols = [.. classes
                .Where(static symbol => !symbol.IsGenericType)
                .Distinct(SymbolEqualityComparer.Default)
                .OfType<INamedTypeSymbol>()
                .OrderBy(static symbol =>
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))];

            var source = new StringBuilder();

            source.AppendLine("""
                // <auto-generated />

                #nullable enable

                using System.Runtime.CompilerServices;
                using DevoidEngine.Metadata;

                namespace DevoidEngine.Generated;

                internal static class ClassDBRegistry
                {
                    [ModuleInitializer]
                    internal static void Initialize()
                    {
                """);

            foreach (INamedTypeSymbol symbol in symbols)
            {
                string classDBName = GetClassDBName(symbol);

                source.AppendLine(
                    $"        ClassDB.Register({classDBName}.Info);");
            }

            source.AppendLine("""
                    }
                }
                """);

            context.AddSource(
                "ClassDBRegistry.g.cs",
                source.ToString());
        }

        private static string GetClassDBName(INamedTypeSymbol symbol)
        {
            return $"{symbol.Name}_ClassDB";
        }
    }
}