<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<PermitDynamicIL>false</PermitDynamicIL>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DevoidEngine.SourceGen\DevoidEngine.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="Sharploud" Version="2020.2.7" />
    <PackageReference Include="StbiSharp" Version="1.2.1" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevoidGPU\DevoidGPU.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="./Content/**/*.*" CopyToOutputDirectory="PreserveNewest" Visible="true" />
	</ItemGroup>

	<ItemGroup>
		<None Include="./runtimes/**" CopyToOutputDirectory="PreserveNewest" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SharpFont">
			<HintPath>Lib\SharpFont.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Content\DevoidShaderDescriptors\ui_textsdf_mat.dsd">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\ui_textsdf.vert.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\ui_textsdf.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Lib\SharpFont.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<ItemGroup>
	  <None Update="Content\DevoidShaderDescriptors\ui_mat.dsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\DevoidShaderDescriptors\pbr_mat.dsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\ui.frag.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\ui.vert.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky_procedural.frag.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky_procedural.vert.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Lib\" />
	</ItemGroup>

</Project>
