<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<PermitDynamicIL>false</PermitDynamicIL>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DevoidEngine.SourceGen\DevoidEngine.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<Target Name="GenerateEnginePaths" BeforeTargets="BeforeCompile" Condition="'$(Configuration)' == 'Debug'">
		<PropertyGroup>
			<GeneratedCodeLines>
				namespace DevoidEngine.Core%3b
				internal static class BuildInfo
				{
				public const string EngineRoot = @"$(MSBuildProjectDirectory)"%3b
				}
			</GeneratedCodeLines>
		</PropertyGroup>

		<WriteLinesToFile File="$(IntermediateOutputPath)EnginePaths.g.cs" Overwrite="true" Lines="$(GeneratedCodeLines)" />

		<ItemGroup>
			<Compile Include="$(IntermediateOutputPath)EnginePaths.g.cs" />
		</ItemGroup>
	</Target>


	<ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="Sharploud" Version="2020.2.7" />
    <PackageReference Include="StbiSharp" Version="1.2.1" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevoidGPU\DevoidGPU.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="./Content/**/*.*" CopyToOutputDirectory="PreserveNewest" Visible="true" />
	</ItemGroup>

	<ItemGroup>
		<None Include="./runtimes/**" CopyToOutputDirectory="PreserveNewest" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SharpFont">
			<HintPath>Lib\SharpFont.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Content\DevoidShaderDescriptors\probe_debug.dsd">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\Common\ProbeGI.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\gtvbao.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\imgui.vert.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\imgui.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\bloom_process.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\probe_relocate_update.comp.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\tonemap.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\brdf.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\sky_cubemap.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\prefilter.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\panorama_to_cubemap.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\sh9_reduce.comp.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\ui_textsdf.vert.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\ui_textsdf.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\gizmo.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\probe_debug.frag.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Content\Shaders\probe_debug.vert.hlsl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Visible>true</Visible>
		</None>
		<None Update="Lib\SharpFont.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<ItemGroup>
	  <None Update="Content\Shaders\ui.frag.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\ui.vert.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky_procedural.frag.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky.vert.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Lib\" />
	</ItemGroup>

</Project>
