<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<PermitDynamicIL>false</PermitDynamicIL>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="Sharploud" Version="2020.2.7" />
    <PackageReference Include="StbiSharp" Version="1.2.1" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevoidGPU\DevoidGPU.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="./Content/**/*.*" CopyToOutputDirectory="PreserveNewest" Visible="true" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Content\DevoidShaderDescriptors\pbr_mat.dsd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky_procedural.frag.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	  <None Update="Content\Shaders\sky_procedural.vert.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Visible>true</Visible>
	  </None>
	</ItemGroup>

</Project>
